"use client";
import {FormEvent,useEffect,useState} from "react";
type Task={id:string;title:string;status:string;priority:string;due:string;source:string};type Plan={id:string;title:string;status:string;deadline:string};type Event={id:string;title:string;date:string;type:string};
const nav=[['dashboard','⌂','Übersicht'],['webmail','✉','Webmail'],['calendar','□','Kalender'],['monthly','◫','Monatssteuerung'],['tasks','✓','Aufgaben'],['customers','◇','Kunden'],['communication','○','Kommunikation'],['contacts','♙','Kontakte'],['finance','€','Finanzen'],['team','♟','Team & Rollen'],['tools','▦','Tools']] as const;
const demoTools=[['Notion','N'],['Google Drive','G'],['Canva','C'],['Meta Business','M'],['ChatGPT','AI']];
export default function WorkspaceApp(){const[page,setPage]=useState('dashboard');const[tasks,setTasks]=useState<Task[]>([]);const[plans,setPlans]=useState<Plan[]>([]);const[events,setEvents]=useState<Event[]>([]);const[demo,setDemo]=useState(true);const[modal,setModal]=useState<string|null>(null);const[toast,setToast]=useState('');useEffect(()=>{fetch('/api/dashboard').then(r=>r.json()).then(d=>{setTasks(d.tasks||[]);setPlans(d.plans||[]);setEvents(d.events||[]);setDemo(Boolean(d.demo))}).catch(()=>{})},[]);function notify(s:string){setToast(s);setTimeout(()=>setToast(''),2200)};async function addTask(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),title=String(f.get('title')||'');const task={id:crypto.randomUUID(),title,status:'To-do',priority:String(f.get('priority')||'Mittel'),due:String(f.get('due')||''),source:'Intern'};setTasks(x=>[task,...x]);setModal(null);notify(demo?'Aufgabe lokal im Demomodus ergänzt':'Aufgabe wird in Notion gespeichert');if(!demo)await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(task)});}
const open=tasks.filter(t=>t.status!=='Abgeschlossen');const title=nav.find(x=>x[0]===page)?.[2]||'Arbeitszentrale';return <div className="app"><aside><div className="brand"><img src="/braventis-logo.png" alt="BRAVENTIS"/></div><nav>{nav.map(([id,icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><i>{icon}</i>{label}</button>)}</nav><div className="profile"><b>PP</b><span>Patrick Pigler<small>Geschäftsführung</small></span></div></aside><main><header><strong>{title}</strong><div><button className="circle">⌕</button><button className="circle">◇</button><button className="circle">PP</button></div></header><div className="content">{demo&&<div className="demo">Demomodus · Für Live-Daten werden die Notion-Umgebungsvariablen in Vercel hinterlegt.</div>}{page==='dashboard'&&<Dashboard tasks={open} plans={plans} events={events} go={setPage}/>} {page==='tasks'&&<Tasks tasks={tasks} setTasks={setTasks} add={()=>setModal('task')}/>} {page==='monthly'&&<Monthly plans={plans} notify={notify}/>} {page==='finance'&&<Finance notify={notify}/>} {page==='calendar'&&<Calendar events={events} notify={notify}/>} {page==='webmail'&&<Webmail notify={notify}/>} {page==='customers'&&<Customers/>} {page==='communication'&&<Communication notify={notify}/>} {page==='contacts'&&<Contacts notify={notify}/>} {page==='team'&&<Team/>} {page==='tools'&&<Tools/>}</div></main><div className="mobilebar">{[['dashboard','⌂','Start'],['tasks','✓','Aufgaben'],['monthly','◫','Monat'],['finance','€','Finanzen'],['tools','•••','Mehr']].map(x=><button key={x[0]} onClick={()=>setPage(x[0])}>{x[1]}<small>{x[2]}</small></button>)}</div>{modal==='task'&&<Modal close={()=>setModal(null)}><h2>Neue Aufgabe</h2><form onSubmit={addTask}><label>Titel<input name="title" required placeholder="Konkretes Arbeitsergebnis"/></label><div className="formgrid"><label>Priorität<select name="priority" defaultValue="Mittel"><option>Hoch</option><option>Mittel</option><option>Niedrig</option></select></label><label>Fällig<input name="due" type="date"/></label></div><button className="primary">Aufgabe anlegen</button></form></Modal>} {toast&&<div className="toast">{toast}</div>}</div>}
function Hero({eyebrow,title,sub,action}:{eyebrow:string,title:string,sub:string,action?:React.ReactNode}){return <div className="hero"><div><em>{eyebrow}</em><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Dashboard({tasks,plans,events,go}:{tasks:Task[];plans:Plan[];events:Event[];go:(s:string)=>void}){return <><Hero eyebrow="MITTWOCH, 23. SEPTEMBER 2026" title="Guten Morgen, Patrick." sub="Was heute Aufmerksamkeit braucht – ruhig, klar und priorisiert." action={<button className="primary" onClick={()=>go('tasks')}>Meine Aufgaben öffnen</button>}/><section className="quote"><em>IMPULS DES TAGES</em><blockquote>„Klarheit entsteht, wenn der nächste sinnvolle Schritt sichtbar wird.“</blockquote><p>BRAVENTIS Arbeitsimpuls</p></section><h2>Heute im Blick</h2><div className="metrics"><Metric cls="violet" label="Offene Aufgaben" value={String(tasks.length||0)} note="chronologisch priorisiert"/><Metric cls="teal" label="Nächster Termin" value={events[0]?.date?.slice(11,16)||'–'} note={events[0]?.title||'Noch kein Termin'}/><Metric cls="blue" label="Webmail" value="–" note="Integration ausstehend"/><Metric cls="gold" label="Freigaben" value={String(plans.filter(p=>p.status==='Eingereicht').length)} note="eingereichte Monatspläne"/></div><div className="twocol"><Card title="Tagesfokus">{tasks.slice(0,4).map(t=><TaskRow key={t.id} t={t}/>)}</Card><Card title="Monatssteuerung">{plans.slice(0,4).map(p=><div className="listrow" key={p.id}><div><b>{p.title}</b><small>{p.deadline||'Termin offen'}</small></div><span>{p.status}</span></div>)}</Card></div></>}
function Metric({cls,label,value,note}:{cls:string;label:string;value:string;note:string}){return <div className={'metric '+cls}><small>{label}</small><strong>{value}</strong><p>{note}</p></div>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="card"><h3>{title}</h3>{children}</section>}
function TaskRow({t,done}:{t:Task;done?:()=>void}){return <div className="taskrow"><button className="check" onClick={done}>✓</button><div><b>{t.title}</b><small>{t.source} · {t.due||'ohne Termin'}</small></div><span className={'pill '+t.priority.toLowerCase()}>{t.priority}</span></div>}
function Tasks({tasks,setTasks,add}:{tasks:Task[];setTasks:(f:(x:Task[])=>Task[])=>void;add:()=>void}){return <><Hero eyebrow="PLAN · KUNDE · PROJEKT · POOL" title="Aufgaben" sub="Eine priorisierte Liste mit klarer Herkunft und chronologischer Reihenfolge." action={<button className="primary" onClick={add}>+ Aufgabe</button>}/><Card title="Alle Aufgaben">{tasks.length?tasks.map(t=><TaskRow key={t.id} t={t} done={()=>setTasks(x=>x.map(a=>a.id===t.id?{...a,status:'Abgeschlossen'}:a))}/>):<Empty text="Noch keine Aufgaben vorhanden."/>}</Card><h2>Allgemeiner Aufgabenpool</h2><div className="cards3"><Mini title="Flyer Herbstaktion" tag="Marketing"/><Mini title="Blogartikel vorbereiten" tag="Website"/><Mini title="Prozess dokumentieren" tag="Automatisierung"/></div></>}
function Monthly({plans,notify}:{plans:Plan[];notify:(s:string)=>void}){return <><Hero eyebrow="BRAVENTIS MONATSRHYTHMUS" title="Monatssteuerung" sub="Vom einheitlichen Konzept zur freigegebenen und ausführbaren Aufgabenliste."/><div className="steps">{['Entwurf','Eingereicht','Prüfung','Ergänzung','Freigegeben','Umsetzung','Abschluss'].map((x,i)=><span className={i===2?'on':''} key={x}>{i+1} · {x}</span>)}</div><Card title="Abteilungspläne">{plans.map(p=><div className="listrow" key={p.id}><div><b>{p.title}</b><small>Einreichung: {p.deadline||'offen'}</small></div><span className="pill mittel">{p.status}</span><button className="secondary" onClick={()=>notify('Freigabe wird nach Live-Anbindung in Notion gespeichert')}>Öffnen</button></div>)}</Card></>}
function Finance({notify}:{notify:(s:string)=>void}){return <><Hero eyebrow="GESCHÜTZTER GESCHÄFTSBEREICH" title="Finanzen & Buchhaltung" sub="Belege digitalisieren, Rechnungen prüfen und den Monat wirtschaftlich überblicken." action={<button className="goldbtn" onClick={()=>notify('Belegscanner wird in der OCR-Ausbaustufe aktiviert')}>Kamera öffnen</button>}/><section className="financeHero"><em>SEPTEMBER 2026</em><h2>Finanzieller Monatsüberblick</h2><p>Live-Kennzahlen erscheinen nach Anbindung der Finanzdaten.</p><div className="finmetrics"><span><small>Einnahmen</small><b>–</b></span><span><small>Ausgaben</small><b>–</b></span><span><small>Ergebnis</small><b>–</b></span><span><small>Offene Belege</small><b>0</b></span></div></section><div className="cards3"><Mini title="Foto-zu-PDF-Scanner" tag="Belege"/><Mini title="Eingangsrechnungen" tag="Prüfung"/><Mini title="Kundenrechnungen" tag="Offen"/></div></>}
function Calendar({events,notify}:{events:Event[];notify:(s:string)=>void}){return <><Hero eyebrow="ZEIT & VERFÜGBARKEIT" title="Kalender" sub="Persönliche, Team-, Kunden- und Projekttermine." action={<button className="primary" onClick={()=>notify('Terminformular wird als nächstes live angebunden')}>+ Neuer Termin</button>}/><Card title="Nächste Termine">{events.length?events.map(e=><div className="listrow" key={e.id}><div><b>{e.title}</b><small>{e.date}</small></div><span>{e.type}</span></div>):<Empty text="Noch keine Termine vorhanden."/>}</Card></>}
function Webmail({notify}:{notify:(s:string)=>void}){return <><Hero eyebrow="ZENTRALE NACHRICHTEN" title="Webmail" sub="E-Mails lesen, beantworten und mit Aufgaben oder Kunden verknüpfen." action={<button className="primary" onClick={()=>notify('Webmail-Anbieter ist noch nicht verbunden')}>+ Neue E-Mail</button>}/><div className="mail"><Card title="Posteingang"><Empty text="Nach Verbindung des Mail-Anbieters erscheinen Nachrichten hier."/></Card><Card title="Nachricht"><p>Webmail bleibt bis zur Auswahl des Providers im Integrationsmodus.</p></Card></div></>}
function Customers(){return <><Hero eyebrow="360° KUNDENANSICHT" title="Kunden" sub="Kontakte, Leistungen, Termine, Aufgaben, Dateien und Kommunikation an einem Ort."/><div className="cards3"><Mini title="Daltec" tag="Aktiv"/><Mini title="Kundenstruktur" tag="Notion"/></div></>}
function Communication({notify}:{notify:(s:string)=>void}){return <><Hero eyebrow="KONTEXT STATT DOPPELKOMMUNIKATION" title="Kommunikation" sub="Direktnachrichten, Teamräume, Ankündigungen und Projekträume."/><div className="twocol"><Card title="Für mich"><div className="listrow"><div><b>Marketing</b><small>Monatsplan wurde eingereicht</small></div><span>Neu</span></div></Card><Card title="Räume">{['Alle','Geschäftsführung','Marketing','Sales','Website','Automatisierung'].map(x=><button className="room" key={x} onClick={()=>notify(x+' geöffnet')}>{x}</button>)}</Card></div></>}
function Contacts({notify}:{notify:(s:string)=>void}){return <><Hero eyebrow="TEAM ERREICHBAR HALTEN" title="Kontakte" sub="Direkt schreiben, anrufen, Video starten oder Bildschirm teilen."/><div className="cards3">{['Michael Schneider','Philipp','Luca Schneider'].map(x=><section className="card" key={x}><div className="person"><b>{x.split(' ').map(a=>a[0]).join('')}</b><span><strong>{x}</strong><small>Rolle ergänzen</small></span></div><button className="secondary" onClick={()=>notify('Nachricht an '+x)}>Nachricht</button></section>)}</div></>}
function Team(){return <><Hero eyebrow="ZUGRIFF & VERANTWORTUNG" title="Team & Rollen" sub="Rolle, Abteilung, Führungskraft und Zugriffsbereich beim Einladen festlegen."/><div className="roles">{[['GF','Geschäftsführung / Inhaber','Vollzugriff · Freigaben · Finanzen'],['TL','Abteilungsleitung','Monatspläne · Aufgaben · Team'],['MA','Mitarbeiter/in','Eigene Aufgaben · Abteilung · Pool'],['EX','Extern / Gast','Nur freigegebene Kontexte']].map(x=><div className="role" key={x[0]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span></div>)}</div></>}
function Tools(){return <><Hero eyebrow="SCHNELLZUGRIFF" title="Tools" sub="Die wichtigsten Arbeitswerkzeuge an einem ruhigen, einheitlichen Ort."/><div className="tools">{demoTools.map(x=><section className="card" key={x[0]}><b className="toolicon">{x[1]}</b><h3>{x[0]}</h3></section>)}</div></>}
function Mini({title,tag}:{title:string;tag:string}){return <section className="card mini"><span>{tag}</span><h3>{title}</h3><p>Details werden im jeweiligen Bereich ergänzt.</p><button className="secondary">Öffnen</button></section>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function Modal({children,close}:{children:React.ReactNode;close:()=>void}){return <div className="overlay" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><div className="modal"><button className="x" onClick={close}>×</button>{children}</div></div>}
